name: Build and Release (Windows)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

# REQUIRED so the built-in GITHUB_TOKEN can create releases and upload assets
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Optional, keeps console output UTF-8 friendly
      - name: Set code page to UTF-8
        shell: pwsh
        run: chcp 65001

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      # Validate secrets needed for embedding (fail fast if missing)
      - name: Validate embedding secrets
        shell: pwsh
        run: |
          if (-not "${{ secrets.LD_API_KEY }}") { throw "Missing secret: LD_API_KEY" }
          if (-not "${{ secrets.PROJECT_KEY }}") { throw "Missing secret: PROJECT_KEY" }
          # Optional PAT for private repo updater. If empty, updater will work for public repos only.
          if (-not "${{ secrets.GH_TOKEN_APP }}") { Write-Host "[WARN] GH_TOKEN_APP not set (private repo updater downloads will fail)" }

      # Always embed internal config into the EXE at build time (internal-only)
      - name: Write config.json (internal build)
        shell: pwsh
        run: |
          $obj = [ordered]@{
            LAUNCHDARKLY_API_KEY = "${{ secrets.LD_API_KEY }}"
            PROJECT_KEY          = "${{ secrets.PROJECT_KEY }}"
            GITHUB_TOKEN         = "${{ secrets.GH_TOKEN_APP }}"
            LOG_FILE             = "feature_flag.log"
            HISTORY_FILE         = "autocomplete_history.json"
          }
          $json = ($obj | ConvertTo-Json -Compress)
          Set-Content -Path config.json -Value $json -Encoding UTF8

      - name: Build EXE
        shell: pwsh
        run: |
          .\build.ps1 -EmbedConfig -ConfigPath ".\config.json" -Clean

      # Secure cleanup: remove temporary config.json to ensure no config file is shipped
      - name: Cleanup temporary config
        if: always()
        shell: pwsh
        run: |
          if (Test-Path config.json) { Remove-Item -Force config.json }

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: FeatureFlagManager
          path: dist/FeatureFlagManager.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Feature Flag Manager ${{ github.ref_name }}"
          body: "Automated build for ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: |
            dist/FeatureFlagManager.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # built-in token